language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION="2.2.*"
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"

install:
    # Configure appropriate symfony packages
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} symfony/symfony:${SYMFONY_VERSION} --no-update

    # Manually configure build tools (excluding HHVM which lacks libxml)
    - if [[ "${TRAVIS_PHP_VERSION}" == "hhvm" ]]; then composer require satooshi/php-coveralls:* phpunit/phpcov:2.0.*@dev phpunit/phpunit:4.0.*@dev phpunit/php-code-coverage:2.0.*@dev phpunit/phpunit-mock-objects:2.0.*@dev sebastian/environment:1.*@dev --no-update; fi

    # Install deps
    - composer install --no-dev

script:
    - mkdir -p build/logs
    - phpunit -c phpunit-travis.xml --coverage-clover=build/logs/clover-${SYMFONY_VERSION}-${TRAVIS_PHP_VERSION}.xml

after_script:

    # Combine coverage reports
    - if [[ "${TRAVIS_PHP_VERSION}" == "hhvm" ]]; then ./bin/phpcov merge --clover coverage.xml build/logs/; fi

    # Upload coverage to scrutinizer
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

    # Upload coverage to coveralls.io
    - php bin/coveralls -v
