language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION="2.2.*"
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"

install:
    # Avoid installing development deps, some depend upon libxml which is not available in HHVM
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} symfony/symfony:${SYMFONY_VERSION} satooshi/php-coveralls:* --no-update
    - composer install --no-dev

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover=build/logs/clover-${SYMFONY_VERSION}-${TRAVIS_PHP_VERSION}.xml

after_script:
    # Upload coverage to scrutinizer
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover-*.xml

    # Upload coverage to coveralls.io
    - php bin/coveralls -v
