language: php

php:
  - hhvm
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION="2.2.*"
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.4.*"

install:
    # Configure appropriate symfony packages
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} symfony/symfony:${SYMFONY_VERSION} --no-update

    # Install deps
    - composer install --no-dev

script:
    - mkdir -p build/logs
    - phpunit -c phpunit-travis.xml --coverage-clover=build/logs/clover-${SYMFONY_VERSION}-${TRAVIS_PHP_VERSION}.xml

after_script:

    # Upload coverage to scrutinizer
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

    # Upload coverage to coveralls.io
    - php bin/coveralls -p
